services:
  auth-service:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./services/auth-service:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3001:3001"

  event-service:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./services/event-service:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3002:3002"

  booking-service:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./services/booking-service:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3003:3003"

  payment-service:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./services/payment-service:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3004:3004"

  notification-service:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./services/notification-service:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3005:3005"
